version: 2
updates:
  # Flutter dependencies
  - package-ecosystem: "pub"
    directory: "/loom"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "zz0-0"
    assignees:
      - "zz0-0"
    commit-message:
      prefix: "deps"
      include: "scope"

  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "zz0-0"
    assignees:
      - "zz0-0"
    commit-message:
      prefix: "deps"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "zz0-0"
    assignees:
      - "zz0-0"
    commit-message:
      prefix: "ci"
      include: "scope"
