// Mocks generated by Mockito 5.4.4 from annotations
// in loom/test/mocks/export_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i3;
import 'package:loom/features/export/domain/entities/export_entities.dart'
    as _i5;
import 'package:loom/features/export/presentation/providers/export_provider.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:state_notifier/state_notifier.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExportState_0 extends _i1.SmartFake implements _i2.ExportState {
  _FakeExportState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExportNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockExportNotifier extends _i1.Mock implements _i2.ExportNotifier {
  MockExportNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i3.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i4.Stream<_i2.ExportState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i2.ExportState>.empty(),
      ) as _i4.Stream<_i2.ExportState>);

  @override
  _i2.ExportState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeExportState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.ExportState);

  @override
  set state(_i2.ExportState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ExportState get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeExportState_0(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i2.ExportState);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> exportContent(_i5.ExportRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportContent,
          [request],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i5.ExportFormat> getSupportedFormats() => (super.noSuchMethod(
        Invocation.method(
          #getSupportedFormats,
          [],
        ),
        returnValue: <_i5.ExportFormat>[],
      ) as List<_i5.ExportFormat>);

  @override
  String getFileExtension(_i5.ExportFormat? format) => (super.noSuchMethod(
        Invocation.method(
          #getFileExtension,
          [format],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getFileExtension,
            [format],
          ),
        ),
      ) as String);

  @override
  bool updateShouldNotify(
    _i2.ExportState? old,
    _i2.ExportState? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.RemoveListener addListener(
    _i7.Listener<_i2.ExportState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i3.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
