include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore
  exclude: 
    - build/**
    - lib/src/rust/frb_generated.dart
    - lib/src/rust/frb_generated.*.dart
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true