include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude: 
    - build/**
    - lib/src/rust/frb_generated.*.dart
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false