name: loom
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.5.4
description: A new Flutter project.
dependencies:
  adaptive_theme: ^3.6.0
  cupertino_icons: ^1.0.8
  dynamic_color: ^1.6.8
  file_picker: ^10.3.2
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_highlight: ^0.7.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_rust_bridge: 2.11.1
  freezed_annotation: ^2.4.4
  intl: any
  lucide_icons: ^0.257.0
  meta: ^1.15.0
  path: ^1.9.0
  riverpod_annotation: ^2.3.5
  rust_lib_loom:
    path: rust_builder
  shared_preferences: ^2.2.3
  window_manager: ^0.3.9
dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  integration_test:
    sdk: flutter
  intl_utils: ^2.8.8
  mockito: ^5.4.4
  pubspec_dependency_sorter: ^1.0.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^6.0.0
flutter:
  uses-material-design: true
  generate: true
