// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:loom/src/rust/frb_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);
